//
// Copyright (c) 2024 INRIA
//

#pragma once

#ifndef PINOCCHIO_DISABLE_UNSUPPORTED_WARNINGS
  #include "pinocchio/deprecated.hpp"
  #define PINOCCHIO_UNSUPPORTED PINOCCHIO_DEPRECATED
  #define PINOCCHIO_UNSUPPORTED_MESSAGE PINOCCHIO_DEPRECATED_MESSAGE
#else
  #define PINOCCHIO_UNSUPPORTED
  #define PINOCCHIO_UNSUPPORTED_MESSAGE(message)
#endif // ifndef PINOCCHIO_DISABLE_UNSUPPORTED_WARNINGS
