%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-pinocchio
Version:        2.6.17
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pinocchio package

License:        BSD-2
URL:            https://github.com/stack-of-tasks/pinocchio
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python%{python3_pkgversion}-devel
Requires:       eigen3-devel
Requires:       python%{python3_pkgversion}-devel
Requires:       python%{python3_pkgversion}-numpy
Requires:       ros-humble-eigenpy
Requires:       ros-humble-hpp-fcl
Requires:       urdfdom-devel
Requires:       ros-humble-ros-workspace
BuildRequires:  boost-devel
BuildRequires:  boost-python%{python3_pkgversion}-devel
BuildRequires:  clang
BuildRequires:  cmake3
BuildRequires:  doxygen
BuildRequires:  eigen3-devel
BuildRequires:  git
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-numpy
BuildRequires:  ros-humble-eigenpy
BuildRequires:  ros-humble-hpp-fcl
BuildRequires:  urdfdom-devel
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A fast and flexible implementation of Rigid Body Dynamics algorithms and their
analytical derivatives.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Wed Feb 15 2023 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.17-1
- Autogenerated by Bloom

* Fri Feb 03 2023 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.16-1
- Autogenerated by Bloom

* Wed Feb 01 2023 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.15-1
- Autogenerated by Bloom

* Mon Jan 30 2023 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.14-3
- Autogenerated by Bloom

* Mon Jan 30 2023 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.14-2
- Autogenerated by Bloom

* Sun Jan 22 2023 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.14-1
- Autogenerated by Bloom

* Sun Nov 06 2022 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.12-1
- Autogenerated by Bloom

* Tue Oct 25 2022 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.11-1
- Autogenerated by Bloom

* Tue Oct 11 2022 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.10-3
- Autogenerated by Bloom

* Thu Sep 15 2022 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.10-2
- Autogenerated by Bloom

* Thu Sep 15 2022 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.10-1
- Autogenerated by Bloom

* Sat Aug 13 2022 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.9-1
- Autogenerated by Bloom

