%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-pinocchio
Version:        3.6.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pinocchio package

License:        BSD-2
URL:            https://github.com/stack-of-tasks/pinocchio
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python%{python3_pkgversion}-devel
Requires:       eigen3-devel
Requires:       python%{python3_pkgversion}-devel
Requires:       python%{python3_pkgversion}-numpy
Requires:       ros-jazzy-eigenpy
Requires:       ros-jazzy-hpp-fcl
Requires:       ros-jazzy-ros-environment
Requires:       ros-jazzy-urdfdom
Requires:       ros-jazzy-ros-workspace
BuildRequires:  boost-devel
BuildRequires:  boost-python%{python3_pkgversion}-devel
BuildRequires:  clang
BuildRequires:  cmake3
BuildRequires:  doxygen
BuildRequires:  eigen3-devel
BuildRequires:  git
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-numpy
BuildRequires:  ros-jazzy-eigenpy
BuildRequires:  ros-jazzy-hpp-fcl
BuildRequires:  ros-jazzy-ros-environment
BuildRequires:  ros-jazzy-urdfdom
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A fast and flexible implementation of Rigid Body Dynamics algorithms and their
analytical derivatives.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Mon Jun 23 2025 Justin Carpentier <justin.carpentier@inria.fr> - 3.6.0-1
- Autogenerated by Bloom

* Thu Apr 24 2025 Justin Carpentier <justin.carpentier@inria.fr> - 3.5.0-1
- Autogenerated by Bloom

* Sat Feb 22 2025 Justin Carpentier <justin.carpentier@inria.fr> - 3.4.0-2
- Autogenerated by Bloom

* Thu Feb 20 2025 Justin Carpentier <justin.carpentier@inria.fr> - 3.4.0-1
- Autogenerated by Bloom

* Sun Dec 08 2024 Justin Carpentier <justin.carpentier@inria.fr> - 3.3.0-1
- Autogenerated by Bloom

* Fri Apr 19 2024 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.21-3
- Autogenerated by Bloom

* Wed Mar 06 2024 Justin Carpentier <justin.carpentier@inria.fr> - 2.6.21-2
- Autogenerated by Bloom

